### ISSUE TITLE
about the draw probabilities

### ISSUE THREAD

**Issue by rinaldi6109** [eminga/cldraw#1]
I've computed the probability of each game by dividing the number of the combinations having such games over the total number of combinations (2002). My numbers are a bit different of yours.
I wonder if this depends on some numerical approximation inside your algorithm or on the fact that not all the combinations are equally probable, but this seems weird to me.
Mumble mumble...

**Comment by eminga** [comment]
Hi,
your second assumption is correct, not all combinations are equally probable.
Here is a nice article which explains why: https://www.fourfourtwo.com/features/champions-league-last-16-draw-probabilities-liverpool-chelsea-tottenham-man-city-real-madrid-barcelona

By the way, you can easily verify this yourself using a 3x3 sample. E.g. in the current CL19/20 draw, draw Napoli vs FC Barcelona, Chelsea FC vs Paris SG, Atalanta vs Liverpool FC, Lyon vs FC Bayern, and Dortmund vs FC Valencia.
For the remaining teams, use a) your combination method and b) calculate the probabilities using the law of total probability. You will see that the results are different.
